using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.SharePoint;
using Voo.University.Models;

namespace Voo.University.Sharepoint
{
    /// <summary>
    /// Class implements template collector of statement report and
    /// apply xslt transformation for our items and convert to html.
    /// As result user will see in the page report generated by xslt
    /// transformation.
    /// </summary>
    public class ReportManager
    {
        public ReportManager(List<SPListItem> items)
        { }

        private void SerializeItems()
        { }

        /// <summary>
        /// Apply xslt template to serialized items.
        /// </summary>
        private String ApplyTemplate(Template template, String source)
        { 
            // TODO: Make response with transformed items.
            return String.Empty;
        }
    }
}
